### ISSUE TITLE
minor esthetic bug: color/shape coding legend of Level 1 is (hard?) copied to Level 2

### ISSUE THREAD

**Issue by StefanoDePascale** [AntheSevenants/NephoVis#68]
minor esthetic bug: color/shape coding legend of Level 1 is (hard?)copied to Level 2 and disappears only when selecting for new color/shaping schemes at Level 2.

**Comment by AntheSevenants** [comment]
Very curious, since I specifically disallow importing data styles from level 1. I'll check it

**Comment by AntheSevenants** [comment]
Discussion continues in https://github.com/AntheSevenants/NephoVis/issues/42.

**Comment by StefanoDePascale** [comment]
I should add that, after talking with Dirk, it might be worthwhile to still store that color/shape information of Level1 when returning from Level2 to Level1. Right now, if one moves from Level 2 to Level1 the color/shape information is being reset.
