### ISSUE TITLE
Margins of token cloud when deselecting the context words cloud

### ISSUE THREAD

**Issue by StefanoDePascale** [AntheSevenants/NephoVis#69]
When one deselects the 'context words cloud' the 'token cloud' does not resize so as to fit the window entirely. In other words, the token cloud is still too large and I need to use the scroll bars.

**Comment by AntheSevenants** [comment]
This behaviour is exactly the same as in the original implementation. I do agree that it's not ideal, so I will try to find a solution.

**Comment by AntheSevenants** [comment]
From https://github.com/AntheSevenants/NephoVis/commit/3f5730730cd36db31ea4a1508984dfd7c4e59f15.

https://user-images.githubusercontent.com/84721952/161009465-dbec891d-0c84-4e1f-aa8f-5bead49673fd.mp4

The parent div styling is a bit wonky so there's only so much I can do. I now resize the parent container depending on whether the FOC plot is shown or not. However, if the user has made an adjustment to the container width, the parent container will *not* resize. I think this is fair behaviour, but I could make it override the user's choice (though I doubt this is good design). I'll close this issue for now, but do tell if the solution is not satisfactory.
