### ISSUE TITLE
Lost tokens don't change transparency

### ISSUE THREAD

**Issue by montesmariana** [AntheSevenants/NephoVis#77]
When tokens are selected by clicking or brushing, particularly in level 2, lost tokens should also change in transparency. Right now they all keep full opacity as if they were selected. This is also the case if the lost token itself is clicked.

![image](https://user-images.githubusercontent.com/54317904/162002088-ecf0d546-4ab3-4950-97a4-5ee8877be8f0.png)

**Comment by AntheSevenants** [comment]
Fixed in https://github.com/AntheSevenants/NephoVis/commit/c4b182bc3f3367be5d6f2b4a18458cf3898b90c4 by setting lost tokens to have the `token.losttoken` class.
