### ISSUE TITLE
Add token count after selection

### ISSUE THREAD

**Issue by montesmariana** [AntheSevenants/NephoVis#78]
This was not part of the previous implementation but I think it could be nice to add, maybe under the title in the Frequency tables.
The tables say how may tokens co-occur with each context word and make different operations, but never mention explicitly how many tokens have been selected.
(This is low priority, just an idea)

**Comment by AntheSevenants** [comment]
Here we go!

![2022-04-13_21-12-14_NephoVis_New_-_Personal_-_Microsoft​_Edge](https://user-images.githubusercontent.com/84721952/163254354-a6f44757-ffef-4581-9a87-2293511796fe.png)
![2022-04-13_21-20-21_NephoVis_New_-_Personal_-_Microsoft​_Edge](https://user-images.githubusercontent.com/84721952/163254362-e9cc2397-e5c1-41f8-a255-4bae4be43763.png)

Implemented in https://github.com/AntheSevenants/NephoVis/commit/fc3b099019813e500b17761003eb54210464c18e.
